config/routes.rb
Rails.application.routes.draw do
  devise_for :admins
  root to: 'items#index'
  resources :items do
    collection do
      get 'information'
      get 'reservation'
    end
  end
  resources :admins
  resources :users do
    resources :outpatients
    resources :somatics

    collection do
      get 'search'
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  extend ActiveHash::Associations::ActiveRecordExtensions
  has_many :outpatients
  has_many :somatics
  has_one_attached :image
  has_many :items

  belongs_to_active_hash :prefecture
  belongs_to_active_hash :know
  belongs_to_active_hash :gender

  def self.search(search)
    if search != ""
      User.where('name LIKE(?)', "%#{search}%")
    else
      User.all
    end
  end

  with_options presence: true do
    validates :name
    validates :birthday
    validates :image
    with_options format: { with: /\A([ァ-ン]|ー)+\z/} do
      validates :kana
    end
    with_options numericality: { other_than: 1, message: 'を選択して下さい' } do
      validates :gender_id
      validates :know_id
      validates :prefecture_id
     end
     validates :postal_code, format: { with: /\A\d{3}[-]\d{4}\z/ }, length: { is: 8 }
     validates :phone_number, format: { with: /\A\d{10,11}\z/ }, length: { maximum: 11 }
     validates :city
     validates :street
     validates :email
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_admin!, only: [:index, :new, :show, :create, :edit, :update]
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  def index
    # @users = User.all.order("name")
    @sss = Outpatient.order(created_at: :desc).first
    @users = User.search(params[:keyword])
    @item = @users.page(params[:page]).per(15)

    # now = Time.now.strftime('%Y%m%d').to_i
    # birthday = @item.birthday.strftime('%Y%m%d').to_i
    # @age = (now - birthday)/10000

  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      redirect_to root_path
    else
      render :new
    end
  end

  def show
    @user = User.find(params[:id])
    @abc = Somatic.where(user_id: @user.id)

    @first = @user.outpatients.order(start_time: :ASC).first
    @last = @user.outpatients.order(start_time: :ASC).last

    now = Time.now.strftime('%Y%m%d').to_i
    birthday = @user.birthday.strftime('%Y%m%d').to_i
    @age = (now - birthday)/10000

  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to user_path(@user.id)
    else
      render :edit
    end
  end

  def destroy
    @user = User.find(params[:id])
    if @user.destroy
      redirect_to root_path
    else
      render :show
    end
  end

  def search
    @users = User.search(params[:keyword])
    @item = @users.page(params[:page]).per(15)
  end

  private
  def user_params
    params.require(:user).permit(:name, :kana, :gender_id, :phone_number, :postal_code, :prefecture_id, :city, :street, :building, :know_id, :email, :birthday, :text, :medical_history, :contraindication, :image)
  end

  def set_user
    @user = User.find(params[:id])
  end
end

app/views/users/_user.html.erb
<div class="user-index">
 <div class="user-index-list">

<table class="table">
  <thead>
    <tr>
    <th scope="col"></th>
      <th scope="col">ID</th>
      <th scope="col">名前</th>
      <th scope="col">性別</th>
      <th scope="col">生年月日(年齢)</th>
    </tr>
  </thead>
  <tbody>
    <% @item.each do |user|%>
    <tr>
    <td class="user-list"><%= image_tag(user.image,class:"user-index-image") %></td>
       <td class="user-list"><%= user.id%></td>
      <td class= "user-list"><%= link_to (user.name),user_path(user.id)%></td>
      <td class="user-list"><%= user.gender.name%></td>
      <td class="user-list"><%= user.birthday.strftime('%Y/%m/%d')%></td>
    </tr>
    <%end%>
  </tbody>
</table>
<div class="kaminari">
<div class="kaminari-list">
<%= paginate @item, theme: 'twitter-bootstrap-4' %>
</div>
</div>
</div>
</div>

app/views/users/_user_form.html.erb
<div class="user-new">
<%= form_with(model: @user, local: true) do |f| %>
<div class="user-image-select">

    <div class="img-upload">
      <div class="weight-bold-text">
        画像を選択してください
        <span class="indispensable">必須</span>
      </div>
      <div class="click-upload">
      <div id="image-list"></div>
        <%= f.file_field :image, class: 'olddd', id:'message_image' %>
      </div>
    </div>
    </div>

 <div class="form-group">
    <label for="exampleFormControlInput1">名前</label>
     <span class="indispensable">必須</span>
<%= f.text_field :name, class:"form-control", id:"exampleFormControlInput1", placeholder:"鈴木太郎" %>
</div>

 <div class="form-group">
  <label for="exampleFormControlInput1">カタカナ</label>  
       <span class="indispensable">必須</span>
   <%= f.text_field :kana, class:"form-control", id:"exampleFormControlInput1", placeholder:"スズキタロウ" %>
   </div>

    <div class="form-group">
  <label for="exampleFormControlInput1">メールアドレス</label>  
       <span class="indispensable">必須</span>
   <%= f.text_field :email, class:"form-control", id:"exampleFormControlInput1", placeholder:"example@gmail.com" %>
   </div>

    <div class="form-group">
  <label for="exampleFormControlInput1">電話番号</label>  
       <span class="indispensable">必須</span>
   <%= f.text_field :phone_number, class:"form-control", id:"exampleFormControlInput1", placeholder:"09012345678" %>
   </div>

       <div class="form-group">
  <label for="exampleFormControlInput1">郵便番号</label>  
       <span class="indispensable">必須</span>
   <%= f.text_field :postal_code, class:"form-control", id:"exampleFormControlInput1", placeholder:"123-4567" %>
   </div>

       <div class="form-group">
  <label for="exampleFormControlInput1">都道府県</label>  
       <span class="indispensable">必須</span>
     <%= f.collection_select(:prefecture_id, Prefecture.all, :id, :name, {}, {class:"form-control", id:"exampleFormControlInput1"}) %>
   </div>

       <div class="form-group">
  <label for="exampleFormControlInput1">市区町村</label>  
       <span class="indispensable">必須</span>
   <%= f.text_field :city, class:"form-control", id:"exampleFormControlInput1", placeholder:"松原市" %>
   </div>

    <div class="form-group">
  <label for="exampleFormControlInput1">番地</label>  
       <span class="indispensable">必須</span>
   <%= f.text_field :street, class:"form-control", id:"exampleFormControlInput1", placeholder:"例：1丁目45番地の9" %>
   </div>

       <div class="form-group">
  <label for="exampleFormControlInput1">建物名</label>  
   <%= f.text_field :building, class:"form-control", id:"exampleFormControlInput1", placeholder:"ギブ住宅101号室" %>
   </div>

 <div class="form-group">
  <label for="exampleFormControlInput1">性別</label>  
       <span class="indispensable">必須</span>
 <%= f.collection_select(:gender_id, Gender.all, :id, :name, {}, {class:"form-control", id:"exampleFormControlInput1"}) %>
 </div>

  <div class="form-group">
  <label for="exampleFormControlInput1">どこで知ったか</label>  
       <span class="indispensable">必須</span>
  <%= f.collection_select(:know_id, Know.all, :id, :name, {}, {class:"form-control", id:"exampleFormControlInput1"}) %>
   </div>

  <div class="form-group">
  <label for="exampleFormControlInput1">既往歴</label>  
   <%= f.text_area :medical_history, class:"form-control", id:"exampleFormControlInput1", placeholder:"" %>
   </div>

  <div class="form-group">
  <label for="exampleFormControlInput1">禁忌</label>  
   <%= f.text_area :contraindication, class:"form-control", id:"exampleFormControlInput1", placeholder:"" %>
   </div>

  <div class="form-group">
    <label for="exampleFormControlTextarea1">特記事項</label>
    <%= f.text_area :text, class:"form-control", id:"exampleFormControlTextarea1", placeholder:"" %>
  </div>

    <label for="exampleFormControlInput1">生年月日</label> 
           <span class="indispensable">必須</span>
      <div class='input-birth-wrap'> 
  <%= raw sprintf(
                  f.date_select(
                    :birthday,
                    class:'select-birth',
                    id:"birth-date",
                    use_month_numbers: true,
                    prompt:'--',
                    start_year: Time.now.year - 50,
                    end_year: (Time.now.year - 5),
                    date_separator: '%s'),
                  "<p> 年 </p>", "<p> 月 </p>") + "<p> 日 </p>" %>
  </div>
  <button type="submit" class="btn btn-primary">登録</button>
<% end %>
</div>

app/views/users/edit.html.erb
<%= render partial: "user_form"%>

app/views/users/new.html.erb
<%= form_with(model: @user, local: true) do |f| %>

<%= f.file_field :image, class: 'olddd', id:'message_image' %>
 <div class="form-group">
    <label for="exampleFormControlInput1">名前</label>
<%= f.text_field :name, class:"form-control", id:"exampleFormControlInput1", placeholder:"名前" %>
</div>

 <div class="form-group">
  <label for="exampleFormControlInput1">カタカナ</label>  
   <%= f.text_field :kana, class:"form-control", id:"exampleFormControlInput1", placeholder:"カタカナ" %>
   </div>

    <div class="form-group">
  <label for="exampleFormControlInput1">メールアドレス</label>  
   <%= f.text_field :email, class:"form-control", id:"exampleFormControlInput1", placeholder:"メールアドレス" %>
   </div>

    <div class="form-group">
  <label for="exampleFormControlInput1">電話番号</label>  
   <%= f.text_field :phone_number, class:"form-control", id:"exampleFormControlInput1", placeholder:"電話番号" %>
   </div>

       <div class="form-group">
  <label for="exampleFormControlInput1">郵便番号</label>  
   <%= f.text_field :postal_code, class:"form-control", id:"exampleFormControlInput1", placeholder:"5801234" %>
   </div>

       <div class="form-group">
  <label for="exampleFormControlInput1">都道府県</label>  
     <%= f.collection_select(:prefecture_id, Prefecture.all, :id, :name, {}, {class:"form-control", id:"exampleFormControlInput1"}) %>
   </div>

       <div class="form-group">
  <label for="exampleFormControlInput1">市区町村</label>  
   <%= f.text_field :city, class:"form-control", id:"exampleFormControlInput1", placeholder:"松原市" %>
   </div>

    <div class="form-group">
  <label for="exampleFormControlInput1">番地</label>  
   <%= f.text_field :street, class:"form-control", id:"exampleFormControlInput1", placeholder:"番地" %>
   </div>

       <div class="form-group">
  <label for="exampleFormControlInput1">建物名</label>  
   <%= f.text_field :building, class:"form-control", id:"exampleFormControlInput1", placeholder:"建物名" %>
   </div>

 <div class="form-group">
  <label for="exampleFormControlInput1">性別</label>  
 <%= f.collection_select(:gender_id, Gender.all, :id, :name, {}, {class:"form-control", id:"exampleFormControlInput1"}) %>
 </div>

  <div class="form-group">
  <label for="exampleFormControlInput1">どこで知ったか</label>  
  <%= f.collection_select(:know_id, Know.all, :id, :name, {}, {class:"form-control", id:"exampleFormControlInput1"}) %>
   </div>

  <div class="form-group">
  <label for="exampleFormControlInput1">既往歴</label>  
   <%= f.text_area :medical_history, class:"form-control", id:"exampleFormControlInput1", placeholder:"建物名" %>
   </div>

  <div class="form-group">
  <label for="exampleFormControlInput1">禁忌</label>  
   <%= f.text_area :contraindication, class:"form-control", id:"exampleFormControlInput1", placeholder:"建物名" %>
   </div>

  <div class="form-group">
    <label for="exampleFormControlTextarea1">特記事項</label>
    <%= f.text_area :text, class:"form-control", id:"exampleFormControlTextarea1", placeholder:"特記事項" %>
  </div>
  <%= raw sprintf(
                  f.date_select(
                    :birthday,
                    class:'form-control',
                    id:"birth-date",
                    use_month_numbers: true,
                    prompt:'--',
                    start_year: Time.now.year - 50,
                    end_year: (Time.now.year - 5),
                    date_separator: '%s'),
                  "<p> 年 </p>", "<p> 月 </p>") + "<p> 日 </p>" %>
  <%= f.submit "登録" ,class:"register-red-btn" %>
<% end %>

app/views/users/show.html.erb
<%# <%= @abc.each do |t|%>
<%# <%= image_tag(t.images) %>
<%# <%end%>

<div class="user-top-contents">

<div class="user-top-image">
<%= image_tag @user.image ,class: "user-image"%>
<div class="user-show-informations">
<div class="user-show-information">
<div class="user-show-edit">
 <%= link_to "編集", edit_user_path(@user.id)%>
</div>
</div>
<div class="user-show-information">
<div class="user-show-delete">
 <%= link_to "削除", user_path(@user.id), method: :delete, data: {confirm: "削除しますか？"} %>
</div>
</div>
</div>
</div>


<div class="user-information">
<div class="user-name">
<%= @user.name%>（<%= @user.kana%>）様
</div>

<div class="user-gender">
<%= @user.gender.name%>
</div>

<div class="user-birthday">
<%= @user.birthday.strftime('%Y/%m/%d')%>
（<%= @age%>歳）
</div>

<% if @user.outpatients.present?%>

<div class="user-show-visit">
<div class="user-show-visit1">初診日：</div>
<div class="user-show-visit2">
<%= @first.start_time.strftime('%Y/%m/%d')%>
</div>
</div>

<div class="user-show-visit">
<div class="user-show-visit1">最終来院日：</div>
<div class="user-show-visit2">
<%= @last.start_time.strftime('%Y/%m/%d')%>
</div>
</div>

<%else%>
初診日：--
最終来院日：--
<%end%>

<div class="user-style">
<%= link_to "カレンダー", user_outpatients_path(@user),class:"user-calendar"%>


</div>
</div>

</div>

   <div class="user-contents">
    <table class="detail-table">
      <tbody>
        <tr>
          <th class="detail-item">メールアドレス</th>
          <td class="detail-value"><%= @user.email%></td>
        </tr>
        <tr>
          <th class="detail-item">電話番号</th>
          <td class="detail-value"><%= @user.phone_number%></td>
        </tr>
        <tr>
          <th class="detail-item">郵便番号</th>
          <td class="detail-value"><%= @user.postal_code%></td>
        </tr>
        <tr>
          <th class="detail-item">住所</th>
          <td class="detail-value"><%= @user.prefecture.name%> <%= @user.city%> <%= @user.street%> <%= @user.building%></td>
        </tr>
        <tr>
          <th class="detail-item">どこで知ったか</th>
          <td class="detail-value"><%= @user.know.name%></td>
        </tr>
        <% if @user.medical_history.present? %>
        <tr>
          <th class="detail-item">既往歴</th>
          <td class="detail-value"><%= @user.medical_history%></td>
        </tr>
        <%else%>
         <tr>
          <th class="detail-item">既往歴</th>
          <td class="detail-value">--</td>
        </tr>
        <%end%>
        <%if @user.contraindication.present?%>
        <tr>
          <th class="detail-item">禁忌</th>
          <td class="detail-value"><%= @user.contraindication%></td>
        </tr>
        <tr>
        <%else%>
                <tr>
          <th class="detail-item">禁忌</th>
          <td class="detail-value">--</td>
        </tr>
        <tr>
        <%end%>
        <%if @user.text.present?%>
          <th class="detail-items">特記</th>
          <td class="detail-values-user">
          <div class="detail-values-user-text">
          <%= @user.text%>
          </div>
          </td>
        </tr>
          <%else%>
          <th class="detail-items">特記</th>
          <td class="detail-values-user">
          <div class="detail-values-user-text">--
          </div>
          </td>
        </tr>
        <%end%>
      </tbody>
    </table>
    </div>