config/routes.rb
Rails.application.routes.draw do
  devise_for :admins
  root to: 'items#index'
  resources :items do
    collection do
      get 'information'
      get 'reservation'
    end
  end
  resources :admins
  resources :users do
    resources :outpatients
    resources :somatics

    collection do
      get 'search'
    end
  end
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :user
  

  validate :date_before_start
  validate :date_current_today
  validate :date_three_month_end

  def date_before_start
    errors.add(:day, "は過去の日付は選択できません") if day < Date.current
  end
  
  def date_current_today
    errors.add(:day, "は当日は選択できません。予約画面から正しい日付を選択してください。") if day < (Date.current + 1)
  end

  def date_three_month_end
    errors.add(:day, "は3ヶ月以降の日付は選択できません") if (Date.current >> 3) < day
  end


  def self.check_reservation_day(day)
    if day < Date.current
      return "過去の日付は選択できません。正しい日付を選択してください。"
    elsif day < (Date.current + 1)
      return "当日は選択できません。正しい日付を選択してください。"
    elsif (Date.current >> 3) < day
      return "3ヶ月以降の日付は選択できません。正しい日付を選択してください。"
    end
  end



  def self.reservations_after_three_month
    # 今日から3ヶ月先までのデータを取得
    reservations = Item.all.where("day >= ?", Date.current).where("day < ?", Date.current >> 3).order(day: :desc)
    # 配列を作成し、データを格納
    # DBアクセスを減らすために必要なデータを配列にデータを突っ込んでます
    reservation_data = []
    reservations.each do |reservation|
    reservations_hash = {}
    reservations_hash.merge!(day: reservation.day.strftime("%Y-%m-%d"), time: reservation.time, name: reservation.user.name, id:reservation.id)
    reservation_data.push(reservations_hash)
    end
    reservation_data
  end


end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  def index
    @admin = current_admin
    @now = Date.today.month
    @outpatient = Outpatient.all.order(start_time: :DESC)
    @item = @outpatient.page(params[:page]).per(15)

    
    @reserve = Item.all.where(day: Date.current).order("time")
    # now = Time.current
    # @bbb = now.ago(1.days).strftime("%Y-%m-%d")
  end

  def new
    @reservation = Item.new
    @day = params[:day]
    @time = params[:time]
    @start_time = DateTime.parse(@day + " " + @time + " " + "JST")

    message = Item.check_reservation_day(@day.to_date)
    if !!message
      redirect_to @reservation, flash: { alert: message }
    end
  end

  def show
    @reservation = Item.find(params[:id])
  end

  def create
    
    @reservation = Item.new(reservation_params)
    if @reservation.save
      redirect_to item_path @reservation.id
    else
      render :new
    end

  end


  def information
    @month = params[:month] ? Date.parse(params[:month]) : Time.zone.today
    @orders = User.where(created_at: @month.all_month)
    @now = Time.now.strftime('%Y%m%d')
  end

  def reservation
    @reservations = Item.all.where("day >= ?", Date.current).where("day < ?", Date.current >> 3).order(day: :desc)
  end

  private
  def reservation_params
    params.require(:item).permit(:day, :time, :start_time, :user_id)
  end
end

app/helpers/items_helper.rb
module ItemsHelper
  def times
    times = ["10:00",
             "10:30",
             "11:00",
             "11:30",
             "13:00",
             "13:30",
             "14:00",
             "15:00",
             "15:30",
             "16:00",
             "16:30"]
  end

  def check_reservation(reservations, day, time)
    result = false
    reservations_count = reservations.count
    # 取得した予約データにdayとtimeが一致する場合はtrue,一致しない場合はfalseを返します
    if reservations_count > 1
      reservations.each do |reservation|
        result = reservation[:day].eql?(day.strftime("%Y-%m-%d")) && reservation[:time].eql?(time)
        return result if result
      end
    elsif reservations_count == 1
      result = reservations[0][:day].eql?(day.strftime("%Y-%m-%d")) && reservations[0][:time].eql?(time)
      return result if result
    end
    return result
  end
end

app/views/items/index.html.erb
<% if admin_signed_in? %>

<div class="item-index">
<%= link_to new_user_path do %>
<div class="item-box">
<div class="item-contents">
<div class="item-index-image">
<%= image_tag('create.png',class:"item-image")%>
</div>
<div class="item-text">新患登録</div>
</div>
</div>
<%end%>

<%= link_to users_path do%>
<div class="item-box">
<div class="item-contents">
<div class="item-index-image">
<%= image_tag('user.png',class:"item-image")%>
</div>
<div class="item-text">患者様情報</div>
</div>
</div>
<%end%>

<%= link_to information_items_path do%>
<div class="item-box">
<div class="item-contents">
<div class="item-index-image">
<%= image_tag('gurahu.png',class:"item-image")%>
</div>
<div class="item-text">分析ツール</div>
</div>
</div>
<%end%>

<%= link_to reservation_items_path do%>
<div class="item-box">
<div class="item-contents">
<div class="item-index-image">
<%= image_tag('yoyaku.png',class:"item-image")%>
</div>
<div class="item-text">予約ツール</div>
</div>
</div>
<%end%>

<%= link_to edit_admin_path(current_admin.id) do%>
<div class="item-box">
<div class="item-contents">
<div class="item-index-image">
<%= image_tag('admin.png',class:"item-image")%>
</div>
<div class="item-text">管理者編集</div>
</div>
</div>
<%end%>

<%= link_to destroy_admin_session_path, method: :delete do%>
<div class="item-box">
<div class="item-contents">
<div class="item-index-image">
<%= image_tag('logout.png',class:"item-image")%>
</div>
<div class="item-text">ログアウト</div>
</div>
</div>
<%end%>

<%else%>
<div class="top-image">
<%= image_tag("topimage.png",class:"top-image-contents")%>
</div>
<div class="item-index">
<%= link_to new_admin_registration_path do%>
<div class="item-box">
<div class="item-contents">
<div class="item-index-image">
<%= image_tag('singin.png',class:"item-image")%>
</div>
<div class="item-text">管理者登録</div>
</div>
</div>
<%end%>

<%= link_to new_admin_session_path do%>
<div class="item-box">
<div class="item-contents">
<div class="item-index-image">
<%= image_tag('login.png',class:"item-image")%>
</div>
<div class="item-text">ログイン</div>
</div>
</div>
<%end%>
</div>

<%end%>
</div>


<div class="container">
  <div class="row">
    <div class="col-12 text-center">
      <%# <h1>予約画面</h1> %>
      <%# <p>3ヶ月先まで予約することができます。</p> %>
    </div>
  </div>
</div>

 <% if admin_signed_in?%>
<div class="item-index-outpatient">
<%= Time.now.strftime('%Y/%m/%d')%>の予約者リスト
<table class="table">
  <thead>
    <tr>
      <th scope="col">予約時間</th>
      <th scope="col">名前</th>
    </tr>
  </thead>
    <% @reserve.each do |reserve|%>
  <tbody>
    <tr>
      <td><%= reserve.time%></td>
      <td><%= link_to reserve.user.name,user_path(reserve.user.id)%></td>
    </tr>
  </tbody>
  <%end%>
</table>
</div>
<%end%>


 <% if admin_signed_in?%>
<div class="item-index-outpatient">
<table class="table">
  <thead>
    <tr>
      <th scope="col">来院日</th>
      <th scope="col">ID</th>
      <th scope="col">名前</th>
      <th scope="col">金額</th>
    </tr>
  </thead>
    <% @item.each do |outpatient|%>
  <tbody>
    <tr>
      <td><%= outpatient.start_time.strftime('%Y/%m/%d')%></td>
      <td><%= outpatient.user_id%></td>
      <td><%= link_to outpatient.user.name,user_path(outpatient.user.id)%></td>
      <td>¥<%= outpatient.price%></td>
    </tr>
  </tbody>
  <%end%>
</table>
<div class="kaminari">
<div class="kaminari-list">
<%= paginate @item, theme: 'twitter-bootstrap-4' %>
</div>
</div>
</div>
<%end%>

app/views/items/information.html.erb
<div class="information-view">
今月の新患情報
<table class="table table-sm">
  <thead>
    <tr>
      <th scope="col">ID</th>
      <th scope="col">名前</th>
      <th scope="col">生年月日</th>
    </tr>
  </thead>
  <tbody>
    <tr>
    <% @orders.each do |orders|%>
      <td ><%= orders.id%></td>
      <td><%= link_to (orders.name),user_path(orders.id)%></td>
      <td><%= orders.birthday.strftime('%Y/%m/%d')%>（<%=(@now.to_i - (orders.birthday.strftime('%Y%m%d')).to_i)/10000%>歳）</td>
    </tr>
  </tbody>
  <%end%>
</table>
</div>

app/views/items/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-12 text-center title">
      <h1>新規予約画面</h1>
    </div>
    <div class="col-12 mt-3 content">
      <%= form_with model: @reservation, local: true, class: 'form' do |form| %>
      <%#= render 'layouts/error_messages', model: form.object %>
       <div class="day form-group">
        <%= form.label :name, '名前' %>
        <%#= form.text_field :name, class: 'form-control'%>
        <%= form.collection_select(:user_id, User.all, :id, :name, {}, {class:"form-control", id:"exampleFormControlInput1"}) %>
      </div>

      <div class="day form-group">
        <%= form.label :day, '日付' %>
        <%= form.text_field :day, class: 'form-control', value: @day, readonly: true %>
      </div>
      <div class="time form-group">
        <%= form.label :time, '時間' %>
        <%= form.text_field :time, class: 'form-control', value: @time, readonly: true %>
      </div>
      <%= form.hidden_field :start_time, value: @start_time %>
      <div class="submit">
        <%= form.submit value: '予約する', class: 'btn btn-primary mx-auto d-block' %>
      </div>
    <% end %>
    <div class="col-12 text-right">
      <%= link_to '戻る', root_path %>
    </div>
    </div>
  </div>
</div>

app/views/items/reservation.html.erb
    <div class="col-12 mt-3">
      <%= week_calendar events: @reservations do |date, reservations| %>
        <%= date.day %>
      <% end %>
    </div>

app/views/items/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-12 text-center title">
      <h1>予約詳細画面</h1>
    </div>
    <div class="col-12 mt-3 text-center content">
    <div>
        <label><strong>名前：</strong></label>
        <p style="display:inline;"><%= @reservation.user.name %></p>
      </div>
      <div>
        <label><strong>日付：</strong></label>
        <p style="display:inline;"><%= @reservation.day %></p>
      </div>
      <div>
        <label><strong>時間：</strong></label>
        <p style="display:inline;"><%= @reservation.time %></p>
      </div>
    </div>
    <div class="col-12 text-right">
      <%= link_to '予約画面に戻る', root_path %>
    </div>
  </div>
</div>