config/routes.rb
Rails.application.routes.draw do
  devise_for :admins
  root to: 'items#index'
  resources :items do
    collection do
      get 'information'
      get 'reservation'
    end
  end
  resources :admins
  resources :users do
    resources :outpatients
    resources :somatics

    collection do
      get 'search'
    end
  end
end

app/models/outpatient.rb
class Outpatient < ApplicationRecord
  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to :user
  belongs_to_active_hash :medical_category

  with_options presence: true do
    validates :price
    validates :start_time
    with_options numericality: { other_than: 1, message: 'を選択して下さい' } do
    validates :medical_category_id
    end
  end
end

app/controllers/outpatients_controller.rb
class OutpatientsController < ApplicationController
  before_action :authenticate_admin!, only: [:index, :new, :show, :create, :edit, :update]
  before_action :set_outpatient, only: [:index, :show, :edit, :update]

  def index
    @outpatient = Outpatient.new
    @outpatients = Outpatient.where(user_id: @user.id)

     # ハッシュとして全userそれぞれのpriceを取得できる→しかしハッシュのまま
    @sales = Outpatient.group(:user_id).sum(:price)
    @ttt = User.joins(:outpatients).group(:user_id).sum(:price)

    @month_record = @user.outpatients.group("MONTH(start_time)")


    now = Date.today.month
    @now = Time.now
    
    @cccs = Outpatient.where("start_time <= ?", @now)
    @ccc = Outpatient.where("start_time")

    # @dto = @now.ago(30.days)
    # @sdk = Outpatient.where("start_time >= ?", @dto)
    # @so = User.left_joins(:outpatients)
    # .where(outpatients: {user_id: @oaoa.user.id})
    # .where.not(outpatients: {user_id: @sdk.user.id })

        # @aaa = Outpatient.where(:start_time )

    # Time.now-30.day

  end
  def create
    @outpatient = Outpatient.new(outpatient_params)
    @user = @outpatient.user

    if @outpatient.save
      redirect_to "/users/#{@user.id}/outpatients"
    else
      redirect_to "/users/#{@outpatient.user_id}/outpatients"
    end
  end

  def show
    @outpatient = Outpatient.find(params[:id])
    @outpatients = Outpatient.where(user_id: @user.id)
  end

  def edit
    @outpatient = Outpatient.find(params[:id])
    @outpatients = Outpatient.where(user_id: @user.id)
  end

  def update
    @outpatient = Outpatient.find(params[:id])
    if @outpatient.update(outpatient_params)
      redirect_to "/users/#{@user.id}/outpatients/#{@outpatient.id}"
    else
      redirect_to "/users/#{@user.id}/outpatients/#{@outpatient.id}/edit"
    end
  end

  def destroy
    @outpatient = Outpatient.find(params[:id])
    @user = @outpatient.user
    if @outpatient.destroy
      redirect_to "/users/#{@user.id}/outpatients"
    end
  end


  private
  def outpatient_params
    params.require(:outpatient).permit(:price, :text, :medical_category_id, :start_time).merge(user_id: params[:user_id])
  end

  def set_outpatient
    @user = User.find(params[:user_id])
  end
end

app/views/outpatients/_outpatient_form.html.erb
<div class="outpatient-form">
<div class="outpatient-user-name">
 <%= @user.name%>様
 </div>
<div class="outpatient-form-side">

 <div class="outpatient-form-contents">
<%= form_with(model:[@user,@outpatient], local: true) do |form| %>
  <div class="form-group">
   <label for="exampleFormControlInput1">料金</label>
   <%= form.text_field :price, class: "form-control" %>
  </div>
  
  <div class="form-group">
    <label for="exampleFormControlSelect1">施術</label>
     <%= form.collection_select(:medical_category_id, MedicalCategory.all, :id, :name, {}, {class:"form-control", id:"exampleFormControlSelect1"}) %>
  </div>

    <div class="form-group">
    <label for="exampleFormControlSelect1">特記</label>
    <%= form.text_area :text,class: "form-control" %>
  </div>
      <label for="exampleFormControlSelect1">日程</label>
    <div class="form-group">
     <%= form.date_select :start_time, {}, {class: 'form-control', style: 'display: inline-block;width: auto;'} %>
  </div>

    <div class="outpatient-submit">
    <%= form.submit "登録", class:"outpatient-submit-btn" %>
  </div>

<% end %>
</div>
</div>
</div>

app/views/outpatients/_outpatient_text.html.erb
<%= month_calendar events:@outpatients  do |date, events| %>
  <%= date.day %>
  <% events.each do |event| %>
     <div class="outpatient-price-image">
    <a href="/users/<%=@user.id%>/outpatients/<%=event.id%>">¥<%= event.price %></a>
    <% if event.text.present?%>
    <a href="/users/<%=@user.id%>/outpatients/<%=event.id%>"><%=image_tag("file.png" ,class:"outpatient-image") %></a>
    </div>
    <%end%>
  <% end %>
<% end %>
</div>

app/views/outpatients/index.html.erb
<div class="outpatient">
<div class="outpatient-calendar">
<%= render partial: "outpatient_form"%>
<%= render partial: "outpatient_text"%>

<%#=  @sales.each do |sale|%>
<%#= sale.price%>
<%#end%>

<%# <%=@month_record.sum(:medical_category_id)[Date.today.month]%>


</div>
</div>
<%# <%= @sales%>

app/views/outpatients/show.html.erb
<div class="outpatient">
<div class="outpatient-calendar">
<div class="outpatient-form">
<div class="outpatient-user-name">
 <%= @user.name%>様
 </div>


       <%# 商品の情報 %>
       <div class="alala">
    <table class="detail-table">
      <tbody>
        <tr>
          <th class="detail-item">日付</th>
          <td class="detail-value"><%= @outpatient.start_time.strftime('%Y/%m/%d')%></td>
        </tr>
        <tr>
          <th class="detail-item">料金</th>
          <td class="detail-value">¥<%= @outpatient.price%></td>
        </tr>
        <th class="detail-item">施術</th>
          <td class="detail-value"><%= @outpatient.medical_category.name%></td>
        </tr>
        <tr>
          <th class="detail-items">特記</th>
          <td class="detail-values">

          <div class="detail-values-text">
          <%= @outpatient.text%>
          </div>
          </td>
        </tr>
      </tbody>
    </table>
    </div>

<div class="outpatient-btn">
<div class="outpatient-btn-edit">
<a href = "/users/<%=@user.id%>/outpatients/<%=@outpatient.id%>/edit">編集</a>
</div>
<div class="outpatient-btn-delete">
<%= link_to "削除",user_outpatient_path(@outpatient.id), method: :delete, data: {confirm:"削除しますか？"}%>
</div>
<div class="outpatient-btn-return">
<%= link_to "戻る" %>
</div>
</div>
</div>
<%= render partial: "outpatient_text"%>
</div>
</div>
</div>