config/routes.rb
Rails.application.routes.draw do
  devise_for :admins
  root to: 'items#index'
  resources :items do
    collection do
      get 'information'
      get 'reservation'
    end
  end
  resources :admins
  resources :users do
    resources :outpatients
    resources :somatics

    collection do
      get 'search'
    end
  end
end

app/views/layouts/_header.html.erb
<header class="navbar navbar-expand-lg navbar-light bg-light">
      <%= link_to "管理アプリ",root_path,class:"navbar-brand"%>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
          <%= link_to "HOME",root_path,class:"nav-link"%>
          </li>
          <% if admin_signed_in? %>
          <li class="nav-item">
            <%# <a class="nav-link" href="#">管理者編集</a> %>
            <%= link_to "管理者情報",edit_admin_path(current_admin),class:"nav-link"%>
          </li>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              利用者情報
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
              <%= link_to "新患登録",new_user_path,class:"nav-link"%>
              <%= link_to "患者様情報",users_path,class:"nav-link"%>
          </li>
        </ul>
        <%= form_with(url: search_users_path, local: true, method: :get, class: "form-inline my-2 my-lg-0") do |form| %>
  <%= form.text_field :keyword, placeholder: "利用者検索", class: "form-control mr-sm-2" %>
  <%= form.submit "検索", class: "btn btn-outline-success my-2 my-sm-0" %>
<% end %>
  <%else%>
<%= link_to "ログイン", new_admin_session_path, class: "nav-link" %>
 <%= link_to "新規登録", new_admin_registration_path, class: "nav-link" %>
<%end%>

      </div>
    </header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>YuChanApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>